# Generated by Django 5.2.17 on 2026-10-02 04:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentRole',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'assessment_role',
                'ordering': ['role_id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('degree_id', models.AutoField(primary_key=True, serialize=False)),
                ('college', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('degree_level', models.CharField(max_length=10)),
                ('degree_program', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'degree',
                'ordering': ['college', 'department', 'degree_program'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'question',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Plo',
            fields=[
                ('plo_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('degree', models.ForeignKey(db_column='degree_id', on_delete=django.db.models.deletion.CASCADE, related_name='plos', to='surveys.degree')),
            ],
            options={
                'db_table': 'plo',
                'ordering': ['code'],
                'managed': True,
                'unique_together': {('degree', 'code')},
            },
        ),
        migrations.CreateModel(
            name='QuestionPlo',
            fields=[
                ('pk', models.CompositePrimaryKey('question_id', 'plo_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('plo', models.ForeignKey(db_column='plo_id', on_delete=django.db.models.deletion.CASCADE, to='surveys.plo')),
                ('question', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, to='surveys.question')),
            ],
            options={
                'db_table': 'question_plo',
                'managed': True,
                'unique_together': {('question', 'plo')},
            },
        ),
        migrations.AddField(
            model_name='question',
            name='plos',
            field=models.ManyToManyField(related_name='questions', through='surveys.QuestionPlo', to='surveys.plo'),
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('respondent_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_number', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('program_year', models.CharField(max_length=20)),
                ('degree', models.ForeignKey(db_column='degree_id', on_delete=django.db.models.deletion.CASCADE, related_name='respondents', to='surveys.degree')),
            ],
            options={
                'db_table': 'respondent',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assessment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('evaluator_name', models.CharField(blank=True, max_length=150, null=True)),
                ('basis', models.CharField(blank=True, max_length=100, null=True)),
                ('general_comment', models.TextField(blank=True, null=True)),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='surveys.assessmentrole')),
                ('respondent', models.ForeignKey(db_column='respondent_id', on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='surveys.respondent')),
            ],
            options={
                'db_table': 'assessment',
                'ordering': ['-assessment_date'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('assessment', models.ForeignKey(db_column='assessment_id', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.assessment')),
                ('question', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.question')),
            ],
            options={
                'db_table': 'answer',
                'managed': True,
                'unique_together': {('assessment', 'question')},
            },
        ),
    ]
